- hosts: 127.0.0.1
  connection: local
  gather_facts: true
  vars:
    db_url: '{{ db_url }}'
    db_password: '{{ db_password }}'
  tasks:
    - name: Postgres Server properties
      template:
        src: application-postgresql.properties.j2
        dest: "../src/main/resources/application-postgresql.properties"
    - name: print environment.prod.ts
      shell:
        cmd: cat ../src/main/resources/application-postgresql.properties
    - name: mvn package
      command: "mvn clean package"
      args:
        chdir: "../"
    - name: print artefacts
      shell:
        cmd: ls ../target/
    - name: copy artifact
      copy:
        src: ../target/spring-petclinic-rest-2.4.2.jar
        dest: ../installers/spring-petclinic-rest.jar
